language: scala
scala:
- 2.11.7
jdk: oraclejdk8
sudo: false
before_install:
- "./scripts/installMongo mongodb-linux-x86_64-2.6.9 mongo2.6 27018"
- "./scripts/installMongo mongodb-linux-x86_64-3.0.4 mongo3.0 27019"
script: "./scripts/build"
after_success:
- "./scripts/publishJarIfMaster"
- "./sbt coverageAggregate"
- "./sbt coveralls"
- pip install --user codecov && codecov
notifications:
  irc:
    template:
    - "%{result}: %{repository_slug}#%{build_number} (%{branch}@%{commit}: %{author})
      %{build_url}"
  slack:
    secure: KPCXtCAjtlpRQcH7TQtprrf67yIqPVpht9L6/+wbbNd14Tj3x53fiZ3OTabHVx3SL2ZWxbWq+FJGxdIFMyxC/fC0bV9flB7PlRtqHJV1Q7g49odAMAZL7syWr7vFP5bJt+TXuxHvMBihDHFk1Cehy4a1cnrOMReDgqGIFCwQtbI=
env:
  global:
  - LOCAL_MONGODB=true
  - ISOLATED_ENV=true
