language: scala
scala:
- 2.11.7
jdk: oraclejdk8
sudo: false
script: "export MONGO_LINUX=\"MONGO_${MONGO_RELEASE}_LINUX\"; ./scripts/installMongo mongodb-linux-x86_64-${!MONGO_LINUX} mongo 27018 && ./scripts/build $MONGO_RELEASE"
after_success:
- "./scripts/publishJarIfMaster"
# Upload coverage information to coveralls.io
- "./sbt 'project core' coveralls"
# Upload coverage information to codecov.io (BETA)
# Unsure about whether it will do coverage for all the code base as opposed to just core
- pip install --user codecov && codecov
notifications:
  irc:
    template:
    - "%{result}: %{repository_slug}#%{build_number} (%{branch}@%{commit}: %{author})
      %{build_url}"
  slack:
    secure: KPCXtCAjtlpRQcH7TQtprrf67yIqPVpht9L6/+wbbNd14Tj3x53fiZ3OTabHVx3SL2ZWxbWq+FJGxdIFMyxC/fC0bV9flB7PlRtqHJV1Q7g49odAMAZL7syWr7vFP5bJt+TXuxHvMBihDHFk1Cehy4a1cnrOMReDgqGIFCwQtbI=
env:
  matrix:
  - MONGO_RELEASE=2_6
  - MONGO_RELEASE=3_0
  global:
  - LOCAL_MONGODB=true
  - ISOLATED_ENV=true
  - MONGO_2_6_LINUX=2.6.11
  - MONGO_3_0_LINUX=3.0.7
